% finds a bunch of bursting neurons with similar
% voltage dynamics using the neuron-db
% project

function show_these = findSimilarNeurons(n)

show_these = find(n.results.burst_period > .95e3 ...
	            & n.results.burst_period < 1.05e3 ...
	            & n.results.burst_period_std./n.results.burst_period < .01 ...
	            & n.results.duty_cycle_mean > .25 ...
	            & n.results.duty_cycle_mean < .3 ...
	            & n.results.duty_cycle_std./n.results.duty_cycle_mean < .01 ...
	            & n.results.n_spikes_per_burst_mean > 10 ...
	            & n.results.n_spikes_per_burst_mean < 15 ...
	            & n.results.min_V_in_burst_mean > n.results.min_V_mean ...
	            & n.results.min_V_mean < -60);  
